basePath: /
definitions:
  CarCatalog.Car:
    properties:
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/CarCatalog.Human'
      regNum:
        type: string
      year:
        type: integer
    type: object
  CarCatalog.Human:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
  description: API server for Car Catalog App
  title: Car Catalog App API
  version: "1.0"
paths:
  /cars:
    delete:
      description: Delete car from list by regNum
      operationId: delete-by-id
      responses:
        "200":
          description: OK
          schema:
            type: "no"
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete car from list by regNum
    get:
      consumes:
      - application/json
      description: Get All cars with filtration
      operationId: get-all
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/CarCatalog.Car'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get All cars with filtration
    post:
      description: Create new car record
      operationId: add-new
      responses:
        "200":
          description: OK
          schema:
            type: "no"
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new car record
    put:
      description: Change record by ID
      operationId: change-by-id
      responses:
        "200":
          description: OK
          schema:
            type: "no"
        "500":
          description: Internal Server Error
          schema: {}
      summary: Change record by ID
swagger: "2.0"
